### ISSUE TITLE
Upgrade to STAC 1.x

### ISSUE THREAD

**Issue by saberraz** [brazil-data-cube/bdc-stac#195]
Hi, I am not sure if this is a right repo to raise this ticket. 

I am trying to add your data to QGIS through the brand new STAC provider we are building as a core feature. But it appears you are using 0.9.0 version of STAC and hence not possible to read the data:
https://github.com/qgis/QGIS/issues/59693

**Comment by raphaelrpl** [comment]
Hi @saberraz, thanks for opening the ticket.

We are already supporting the STAC 1x in the following address: https://data.inpe.br/bdc/stac/v1

Please, let us know if its working for you.

**Comment by saberraz** [comment]
Brilliant, thanks for the hint @raphaelrpl . I can confirm it works well in QGIS with filtering too. :clap: 
![image](https://github.com/user-attachments/assets/07f4cfb9-2615-4515-b9d4-56c5b8e205a5)
