### ISSUE TITLE
Error 500 in filter by datetime

### ISSUE THREAD

**Issue by OldLipe** [brazil-data-cube/bdc-stac#52]
Hello. I'm doing some tests on the stac.R package and I got a server error in the filter date only.
Example:

`curl http://brazildatacube.dpi.inpe.br/bdc-stac/0.8.0/stac/search?datetime=2018-02-12T23:20:50Z`

But when a collection is provided it works normally.  I would like to know if it makes sense this query without collection, just by the date time. 

Thanks!

**Comment by mzaglia** [comment]
#53 Fixed the issue.
